INSERT INTO journal_settings (journal_id, locale, setting_name, setting_value) VALUES
(1, 'en', 'editorialTeam', '<h3>Editorial Board</h3><h4>Editor-in-Chief</h4><p><em>To be announced</em></p><h4>Deputy Editor</h4><p><em>To be announced</em></p><h4>Section Editors</h4><ul><li><strong>Computer Science and IT</strong> - <em>To be announced</em></li><li><strong>Natural Sciences</strong> - <em>To be announced</em></li><li><strong>Social Sciences and Humanities</strong> - <em>To be announced</em></li><li><strong>Education and Pedagogy</strong> - <em>To be announced</em></li><li><strong>Economics and Management</strong> - <em>To be announced</em></li><li><strong>Medicine and Health Sciences</strong> - <em>To be announced</em></li></ul><h4>Technical Team</h4><ul><li><strong>Managing Editor</strong> - Adapto Editorial Office</li><li><strong>Technical Support</strong> - admin@adapto.kz</li></ul><p><em>We welcome qualified researchers to join our editorial board. Contact: journal@adapto.kz</em></p>')
ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value);

INSERT INTO journal_settings (journal_id, locale, setting_name, setting_value) VALUES
(1, 'ru', 'editorialTeam', '<h3>Редакционная коллегия</h3><h4>Главный редактор</h4><p><em>Будет объявлено</em></p><h4>Заместитель главного редактора</h4><p><em>Будет объявлено</em></p><h4>Редакторы разделов</h4><ul><li><strong>Информатика и ИТ</strong> - <em>Будет объявлено</em></li><li><strong>Естественные науки</strong> - <em>Будет объявлено</em></li><li><strong>Социальные и гуманитарные науки</strong> - <em>Будет объявлено</em></li><li><strong>Образование и педагогика</strong> - <em>Будет объявлено</em></li><li><strong>Экономика и менеджмент</strong> - <em>Будет объявлено</em></li><li><strong>Медицина</strong> - <em>Будет объявлено</em></li></ul><h4>Техническая группа</h4><ul><li><strong>Ответственный редактор</strong> - Редакция Adapto</li><li><strong>Техническая поддержка</strong> - admin@adapto.kz</li></ul><p><em>Мы приглашаем квалифицированных исследователей в редакционную коллегию: journal@adapto.kz</em></p>')
ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value);

INSERT INTO journal_settings (journal_id, locale, setting_name, setting_value) VALUES
(1, 'kk', 'editorialTeam', '<h3>Редакциялық алқа</h3><h4>Бас редактор</h4><p><em>Жариялануы күтілуде</em></p><h4>Бас редактордың орынбасары</h4><p><em>Жариялануы күтілуде</em></p><h4>Бөлім редакторлары</h4><ul><li><strong>Информатика және АТ</strong> - <em>Жариялануы күтілуде</em></li><li><strong>Жаратылыстану ғылымдары</strong> - <em>Жариялануы күтілуде</em></li><li><strong>Әлеуметтік және гуманитарлық ғылымдар</strong> - <em>Жариялануы күтілуде</em></li><li><strong>Білім және педагогика</strong> - <em>Жариялануы күтілуде</em></li><li><strong>Экономика және менеджмент</strong> - <em>Жариялануы күтілуде</em></li><li><strong>Медицина</strong> - <em>Жариялануы күтілуде</em></li></ul><h4>Техникалық топ</h4><ul><li><strong>Жауапты редактор</strong> - Adapto редакциясы</li><li><strong>Техникалық қолдау</strong> - admin@adapto.kz</li></ul><p><em>Біз білікті зерттеушілерді редакциялық алқаға шақырамыз: journal@adapto.kz</em></p>')
ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value);

-- KK About page
UPDATE journal_settings SET setting_value='<h3>Журнал туралы</h3><p>Adapto ғылыми журналы — Adapto компаниясы шығаратын көпсалалы, рецензияланатын, ашық қолжетімді журнал.</p><h3>Тақырыптық бағыт</h3><ul><li>Информатика және ақпараттық технологиялар</li><li>Инженерлік және қолданбалы ғылымдар</li><li>Жаратылыстану ғылымдары</li><li>Әлеуметтік және гуманитарлық ғылымдар</li><li>Білім және педагогика</li><li>Экономика және менеджмент</li><li>Медицина және денсаулық сақтау</li></ul><h3>Ашық қолжетімділік саясаты</h3><p>Барлық мақалалар Creative Commons Attribution 4.0 (CC BY 4.0) лицензиясымен жарияланады.</p><h3>Жарияланым жиілігі</h3><p>Жылына 4 шығарылым (тоқсан сайын).</p><h3>Баспагер</h3><p>Adapto, Қазақстан<br>Email: journal@adapto.kz</p>'
WHERE journal_id=1 AND locale='kk' AND setting_name='about';

-- KK Privacy
INSERT INTO journal_settings (journal_id, locale, setting_name, setting_value) VALUES
(1, 'kk', 'privacyStatement', '<p>Журнал сайтында көрсетілген аттар мен электрондық пошта мекенжайлары тек осы журналдың мақсаттары үшін пайдаланылады және үшінші тараптарға берілмейді.</p>')
ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value);
